/*
	ARCHIVO DE EJECUCION DE PROCEDIMIENTOS CON DATOS
	1.- 21/01/2025	BROSALES	-CREACION DEL ARCHIVO
	2.- 21/01/2025	BROSALES	-CREATE VIEW VWLISTAR_CARGOS
								-CREATE VIEW VWLISTAR_DEPARTAMENTOS
								-CREATE VIEW VWLISTAR_EMPLEADO

*/
USE ECOVISA;

CREATE VIEW [dbo].[VWLISTAR_CARGOS]
AS
	SELECT ID, DESCRIPCION, ESTADO, CASE WHEN ESTADO = 1 THEN 'Activo' ELSE 'Inactivo' END STRESTADO FROM TBLCARGO;
GO

CREATE VIEW [dbo].[VWLISTAR_DEPARTAMENTOS]
AS
	SELECT ID, DESCRIPCION, ESTADO, CASE WHEN ESTADO = 1 THEN 'Activo' ELSE 'Inactivo' END STRESTADO  FROM TBLDEPARTAMENTO;
GO

CREATE OR ALTER VIEW [dbo].[VWLISTAR_EMPLEADO]
AS 
	SELECT EMPLEADO.ID, PRIMER_NOMBRE + ' ' + SEGUNDO_NOMBRE + ' ' + PRIMER_APELLIDO + ' ' + SEGUNDO_APELLIDO AS TRABAJADOR, CEDULA, TELEFONO, CORREO_ELECTRONICO, IDDEPARTAMENTO_LABORAL, DPTO.DESCRIPCION AS DEPARTAMENTO,
		IDCARGO,  CARGO.DESCRIPCION AS CARGO, EMPLEADO.ESTADO
	FROM TBLEMPLEADO EMPLEADO
	INNER JOIN TBLDEPARTAMENTO DPTO ON EMPLEADO.IDDEPARTAMENTO_LABORAL = DPTO.ID
	INNER JOIN TBLCARGO CARGO ON EMPLEADO.IDCARGO = CARGO.ID;
GO

